apiVersion: v1
kind: PersistentVolume
metadata:
  name: files-persistent-volume
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/files"
  claimRef:
    name: files-persistent-volume-claim
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-persistent-volume
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/auth"
  claimRef:
    name: auth-persistent-volume-claim
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
